// Code generated by goctl. DO NOT EDIT.
package types

type GetUserReq struct {
	Id string `json:"id"`
}

type GetUserResp struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}
