// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userclient

import (
	"context"

	"go-zero-prac/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUSerResp = user.CreateUSerResp
	CreateUserReq  = user.CreateUserReq
	GetUserReq     = user.GetUserReq
	GetUserResp    = user.GetUserResp

	User interface {
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		CreateUSer(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUSerResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) CreateUSer(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUSerResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateUSer(ctx, in, opts...)
}
